<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WinDrop.Cli</RootNamespace>
    <AssemblyName>windrop</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WinDrop.Protocol\WinDrop.Protocol.csproj" />
  </ItemGroup>
</Project>
